import { SaxesParser } from 'saxes';
export const LIMITS=Object.freeze({bytes:1024*1024,nodes:8192,gradients:512,stops:128,depth:32,chain:64,attribute:8192,path:65536,pathSegments:4096});
const SVG='http://www.w3.org/2000/svg',XLINK='http://www.w3.org/1999/xlink',XMLNS='http://www.w3.org/2000/xmlns/';
const encoder=new TextEncoder(),decoder=new TextDecoder('utf-8',{fatal:true,ignoreBOM:true});
const fail=message=>{throw Error(message);},check=(ok,message)=>{if(!ok)fail(message);};
const idPattern=/^[A-Za-z_][A-Za-z0-9_.:-]{0,127}$/;
const numberPattern=/^[+-]?(?:\d+(?:\.\d*)?|\.\d+)(?:[eE][+-]?\d+)?$/;
const numeric=(value,min=-1e6,max=1e6)=>numberPattern.test(value)&&Number.isFinite(Number(value))&&Number(value)>=min&&Number(value)<=max;
const geometry={svg:['width','height','viewBox','version','preserveAspectRatio'],defs:[],g:['transform'],path:['d','transform'],rect:['x','y','width','height','rx','ry','transform'],circle:['cx','cy','r','transform'],ellipse:['cx','cy','rx','ry','transform'],line:['x1','y1','x2','y2','transform'],polyline:['points','transform'],polygon:['points','transform'],linearGradient:['x1','y1','x2','y2','gradientUnits','gradientTransform','spreadMethod','href'],radialGradient:['cx','cy','r','fx','fy','gradientUnits','gradientTransform','spreadMethod','href'],stop:['offset'],title:[],desc:[]};
const paintProps=['fill','stroke','color','fill-opacity','stroke-opacity','opacity','stroke-width','stroke-linecap','stroke-linejoin','stroke-miterlimit','fill-rule','stop-color','stop-opacity','display','visibility'];
const colors=/^(?:#[0-9a-fA-F]{6}|#[0-9a-fA-F]{3}|black|white|red|green|blue|none)$/;
function properties(node){const values=new Map();for(const name of paintProps)if(node.attrs[name]!==undefined)values.set(name,node.attrs[name]);
 if(node.attrs.style!==undefined){const seen=new Set();for(const raw of node.attrs.style.split(';')){if(!raw.trim())continue;const colon=raw.indexOf(':');check(colon>0,'Unsupported inline style');const key=raw.slice(0,colon).trim(),value=raw.slice(colon+1).trim();check(paintProps.includes(key)&&!seen.has(key),'Unsupported or repeated inline style property');seen.add(key);values.set(key,value);}}
 for(const [name,value]of values){
  if(['fill','stroke','color','stop-color'].includes(name))check(colors.test(value)||['fill','stroke'].includes(name)&&/^url\(#[A-Za-z_][A-Za-z0-9_.:-]{0,127}\)$/.test(value),'Unsupported color or paint reference');
  else if(name.includes('opacity'))check(numeric(value,0,1),'Opacity must be a number from zero to one');
  else if(['stroke-width','stroke-miterlimit'].includes(name))check(numeric(value,0,10000),'Unsupported stroke number');
  else{const allowed={'stroke-linecap':['butt','round','square'],'stroke-linejoin':['miter','round','bevel'],'fill-rule':['nonzero','evenodd'],display:['inline','none'],visibility:['visible','hidden','collapse']}[name];check(allowed?.includes(value),'Unsupported presentation value');}
 }
 return values;
}
function transform(value){const re=/(matrix|translate|scale|rotate|skewX|skewY)\s*\(([^()]*)\)/gy;let at=0,count=0;while(at<value.length){while(/[\t\r\n ,]/.test(value[at]??'!'))at++;if(at>=value.length)break;re.lastIndex=at;const m=re.exec(value);check(m&&++count<=16,'Unsupported transform');const ns=m[2].trim().split(/[\t\r\n ,]+/);check(ns.every(n=>numeric(n)), 'Unsupported transform number');check(({matrix:[6],translate:[1,2],scale:[1,2],rotate:[1,3],skewX:[1],skewY:[1]})[m[1]].includes(ns.length),'Wrong transform argument count');at=re.lastIndex;}check(count>0,'Empty transform');}
function validatePath(value){
 check(typeof value==='string'&&value.length>0,'Missing path data');const token=/[MmZzLlHhVvCcSsQqTtAa]|[+-]?(?:\d+(?:\.\d*)?|\.\d+)(?:[eE][+-]?\d+)?/gy;
 const arity={M:2,L:2,H:1,V:1,C:6,S:4,Q:4,T:2,A:7,Z:0};let at=0,command=null,numbers=[],segments=0,previous=null,comma=false,first=true;
 function finish(){if(command===null)return;const count=arity[command.toUpperCase()];check(count===0?numbers.length===0:numbers.length>0&&numbers.length%count===0,'Wrong path argument count');segments+=count?numbers.length/count:1;check(segments<=LIMITS.pathSegments,'Path segment limit exceeded');if(command.toUpperCase()==='A')for(let i=0;i<numbers.length;i+=7)check(Number(numbers[i])>=0&&Number(numbers[i+1])>=0&&['0','1'].includes(numbers[i+3])&&['0','1'].includes(numbers[i+4]),'Unsupported arc radius or flag');numbers=[];}
 while(at<value.length){if(/[\t\r\n ]/.test(value[at])){at++;continue;}if(value[at]===','){check(previous==='number'&&!comma,'Invalid path separator');comma=true;at++;continue;}token.lastIndex=at;const match=token.exec(value);check(match,'Malformed path token');const t=match[0];at=token.lastIndex;if(/^[A-Za-z]$/.test(t)){check(!comma,'Invalid path separator');finish();if(first){check(t==='M'||t==='m','Path must start with moveto');first=false;}command=t;previous='command';}else{check(command!==null&&command.toUpperCase()!=='Z'&&numeric(t),'Invalid or unbounded path number');numbers.push(t);previous='number';comma=false;}}
 check(!comma&&!first,'Invalid path ending');finish();
}
function safeAttributes(node){const allowed=new Set(['id','class','style',...paintProps,...geometry[node.name]]);
 for(const a of node.attributes){if(a.uri===XMLNS)continue;const href=a.local==='href'&&a.uri===XLINK&&a.prefix==='xlink'&&['linearGradient','radialGradient'].includes(node.name);check(href||!a.uri&&allowed.has(a.local),'Unsupported SVG attribute or namespace');check(a.value.length<=(a.local==='d'?LIMITS.path:LIMITS.attribute),'SVG attribute exceeds limit');}
 for(const key of ['transform','gradientTransform'])if(node.attrs[key]!==undefined)transform(node.attrs[key]);
 if(node.attrs.gradientUnits!==undefined)check(node.attrs.gradientUnits==='userSpaceOnUse','Only explicit userSpaceOnUse gradients are supported');
 if(node.attrs.spreadMethod!==undefined)check(node.attrs.spreadMethod==='pad','Only pad spreadMethod is supported by this Synfig profile');
 if(node.name==='svg'){check(numeric(node.attrs.width??'',1,8192)&&numeric(node.attrs.height??'',1,8192),'SVG needs bounded numeric width and height');if(node.attrs.viewBox!==undefined){const list=node.attrs.viewBox.trim().split(/[\t\r\n ,]+/);check(list.length===4&&list.every(v=>numeric(v))&&Number(list[2])>0&&Number(list[3])>0,'Unsupported viewBox');}if(node.attrs.preserveAspectRatio!==undefined)check(/^(?:none|x(?:Min|Mid|Max)Y(?:Min|Mid|Max)(?: (?:meet|slice))?)$/.test(node.attrs.preserveAspectRatio),'Unsupported aspect ratio');}
 if(node.name==='path')validatePath(node.attrs.d);
 if(['polygon','polyline'].includes(node.name)){const values=(node.attrs.points??'').trim().split(/[\t\r\n ,]+/);check(values.length>=4&&values.length%2===0&&values.every(v=>numeric(v)),'Unsupported point list');}
 for(const key of geometry[node.name])if(node.attrs[key]!==undefined&&!['d','points','transform','gradientTransform','gradientUnits','spreadMethod','href','viewBox','version','preserveAspectRatio'].includes(key))check(numeric(node.attrs[key]),'Unsupported geometry number');
 return properties(node);
}
export function analyze(bytes){check(bytes instanceof Uint8Array&&bytes.byteLength>0&&bytes.byteLength<=LIMITS.bytes,'SVG input exceeds 1 MiB');let source;try{source=decoder.decode(bytes);}catch{fail('Invalid UTF-8');}
 const nodes=[],stack=[],ids=new Map(),gradients=[],paints=[],defs=[];let start=0,root=null;
 const parser=new SaxesParser({xmlns:true,position:true});
 parser.on('doctype',()=>fail('DTD and entity declarations are unsupported'));parser.on('processinginstruction',()=>fail('Processing instructions and stylesheets are unsupported'));parser.on('cdata',()=>fail('CDATA is unsupported in this profile'));parser.on('xmldecl',d=>check(d.version==='1.0'&&(!d.encoding||/^utf-8$/i.test(d.encoding)),'Only XML 1.0 UTF-8 is supported'));parser.on('error',()=>fail('Malformed XML'));
 parser.on('opentagstart',()=>{start=source.lastIndexOf('<',parser.position-1);});
 parser.on('opentag',tag=>{check(nodes.length<LIMITS.nodes&&stack.length<LIMITS.depth,'SVG structure exceeds limit');check(tag.uri===SVG&&Object.hasOwn(geometry,tag.local),'Unsupported SVG element or namespace');const parent=stack.at(-1),node={name:tag.local,start,end:null,parent,children:[],attrs:{},attributes:Object.values(tag.attributes)};for(const a of node.attributes){if(a.uri===XMLNS)continue;const key=a.uri===XLINK?'xlink:'+a.local:a.local;node.attrs[key]=a.value;}
  if(!parent){check(!root&&node.name==='svg','Expected one SVG root');root=node;}else{parent.children.push(node);const allowed=parent.name==='svg'?['defs','g','path','rect','circle','ellipse','line','polyline','polygon','title','desc']:parent.name==='defs'?['linearGradient','radialGradient']:parent.name==='g'?['g','path','rect','circle','ellipse','line','polyline','polygon','title','desc']:['linearGradient','radialGradient'].includes(parent.name)?['stop']:[];check(allowed.includes(node.name),'Unsupported SVG element placement');}
  if(node.attrs.id!==undefined){check(idPattern.test(node.attrs.id)&&!ids.has(node.attrs.id),'Missing, unsafe or duplicate SVG ID');ids.set(node.attrs.id,node);}
  node.properties=safeAttributes(node);nodes.push(node);stack.push(node);
  if(node.name==='defs')defs.push(node);
  if(['linearGradient','radialGradient'].includes(node.name)){check(node.attrs.id&&gradients.length<LIMITS.gradients,'Every gradient needs a unique bounded ID');gradients.push(node);}
  for(const [property,value]of node.properties)if(value.startsWith('url('))paints.push({node,property,target:value.slice(5,-1)});
  if(node.name==='stop'){check(numeric(node.attrs.offset??'',0,1),'Stop offsets must be numbers from zero to one');check(node.properties.has('stop-color'),'Every stop needs an explicit color');}
 });
 parser.on('text',value=>check(!value.trim()||['title','desc'].includes(stack.at(-1)?.name),'Unexpected SVG text'));parser.on('closetag',()=>{const node=stack.pop();node.end=parser.position;});parser.write(source).close();
 check(root&&defs.length===1&&gradients.length>0,'Expected exactly one defs block with gradients');
 const byId=new Map(gradients.map(n=>[n.attrs.id,n]));
 for(const node of gradients){const plain=node.attrs.href,linked=node.attrs['xlink:href'];check(!(plain!==undefined&&linked!==undefined),'Use one href spelling per gradient');const link=plain??linked;node.target=null;
  if(link!==undefined){check(/^#[A-Za-z_][A-Za-z0-9_.:-]{0,127}$/.test(link),'Only local gradient href fragments are supported');node.target=link.slice(1);const target=byId.get(node.target);check(target,'Missing gradient reference');check(target.name==='linearGradient','References to radial bases are unsupported');check(node.children.length===0,'Own stops plus href are unsupported by this Synfig profile');}
  else check(node.name==='linearGradient'&&node.children.length>0&&node.children.length<=LIMITS.stops,'A base must be a linear gradient with bounded explicit stops');
  if(node.name==='radialGradient')check(node.target,'Radial leaves must reference a linear base');
 }
 for(const p of paints){const node=byId.get(p.target);check(node,'Paint reference must name a local gradient in the defs block');check(node.attrs.gradientUnits==='userSpaceOnUse','Painted gradients need explicit userSpaceOnUse geometry');const keys=node.name==='linearGradient'?['x1','y1','x2','y2']:['cx','cy','r','fx','fy'];check(keys.every(k=>numeric(node.attrs[k]??'')),'Painted gradients need complete numeric geometry');if(node.name==='radialGradient')check(Number(node.attrs.r)>0&&Number(node.attrs.fx)===Number(node.attrs.cx)&&Number(node.attrs.fy)===Number(node.attrs.cy),'Off-center radial focus is unsupported');}
 const ordered=[],state=new Map();function visit(node,depth){check(depth<=LIMITS.chain,'Gradient dependency chain exceeds limit');check(state.get(node)!==1,'Gradient dependency cycle');if(state.get(node)===2)return;state.set(node,1);if(node.target)visit(byId.get(node.target),depth+1);state.set(node,2);ordered.push(node);}for(const node of gradients)visit(node,1);
 for(const paint of paints){const node=byId.get(paint.target);if(node.attrs.gradientTransform===undefined){let parent=node.target?byId.get(node.target):null;while(parent){check(parent.attrs.gradientTransform===undefined,'Inherited gradientTransform is unsupported; painted gradients need their own transform');parent=parent.target?byId.get(parent.target):null;}}}
 let cursor=0;const outside=[];for(const node of gradients){node.raw=source.slice(node.start,node.end);check(node.raw.startsWith('<')&&node.raw.endsWith('>'),'Invalid XML range');outside.push(source.slice(cursor,node.start));cursor=node.end;}outside.push(source.slice(cursor));
 return{source,root,defs:defs[0],nodes,gradients,ordered,byId,outside,paints};
}
export function repair(bytes){const before=analyze(bytes);let source='';for(let i=0;i<before.gradients.length;i++)source+=before.outside[i]+before.ordered[i].raw;source+=before.outside.at(-1);const output=encoder.encode(source),after=analyze(output);check(output.byteLength===bytes.byteLength,'Output byte count changed');check(JSON.stringify(before.outside)===JSON.stringify(after.outside),'Non-gradient bytes changed');for(const node of before.gradients)check(after.byId.get(node.attrs.id)?.raw===node.raw,'Gradient bytes changed');const positions=new Map(after.gradients.map((node,i)=>[node.attrs.id,i]));for(const node of after.gradients)check(!node.target||positions.get(node.target)<positions.get(node.attrs.id),'Dependency order is unresolved');
 const beforeOrder=before.gradients.map(n=>n.attrs.id),afterOrder=after.gradients.map(n=>n.attrs.id);const report={schema:'GradBefore/1',changed:beforeOrder.some((id,i)=>afterOrder[i]!==id),beforeOrder,afterOrder,dependencies:before.gradients.filter(n=>n.target).map(n=>({id:n.attrs.id,base:n.target})),moved:afterOrder.map((id,to)=>({id,from:beforeOrder.indexOf(id),to})).filter(n=>n.from!==n.to),preserved:{gradientBlocks:before.gradients.length,artworkPaintReferences:before.paints.length,bytes:bytes.byteLength},scope:'Only complete gradient blocks are reordered inside one defs. Other bytes, IDs, hrefs, stops and artwork order are unchanged. Static bounded profile; not a general SVG sanitizer or fidelity converter.'};return{output,report};}
